apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sf
  labels:
    app: mynginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      volumes:
      - name: nginx-conf-vol
        configMap:
          name: nginx-sf-conf
          items:
            - key: nginx.conf
              path: nginx.conf
      containers:
      - name: nginx
        image: nginx:1.21.1-alpine
        ports:
        - containerPort: 80
          name: nginx-port-80
        volumeMounts:
        - name: nginx-conf-vol
          mountPath: /etc/nginx
        env:
          - name: NGINX_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-basic
                key: user1
        command: ["/bin/sh", "-c"]
        args: ["apk add apache2-utils && htpasswd -c -b /usr/share/nginx/.htpasswd user1 $(NGINX_PASSWORD) && sleep infinity"]
---
apiVersion: v1
kind: Service
metadata:
  name: sf-webserver
spec:
  selector:
    app: mynginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: nginx-port-80




